name: siri_wave
description: >
  A Flutter package that lets you create visually stunning Siri-style waveforms.
version: 2.0.0
repository: https://github.com/halildurmus/siri_wave
issue_tracker: https://github.com/halildurmus/siri_wave/issues

screenshots:
  - description: Example of the iOS 9 Siri-style waveform.
    path: gifs/ios_9.gif
  - description: Example of the iOS 7 Siri-style waveform.
    path: gifs/ios_7.gif

topics:
  - wave
  - waveform
  - siri

environment:
  sdk: '^3.1.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dartwindows_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  melos: ^3.1.1

flutter:
